<?php

declare(strict_types=1);

namespace futuretek\openapi;

use futuretek\datamapper\DataMapper;
use futuretek\openapi\Middleware\AuthenticationInterface;
use futuretek\openapi\Middleware\AuthorizationInterface;
use futuretek\openapi\Middleware\DefaultAuthentication;
use futuretek\openapi\Middleware\DefaultAuthorization;
use futuretek\openapi\Middleware\DefaultFileHandler;
use futuretek\openapi\Middleware\DefaultLogger;
use futuretek\openapi\Middleware\FileHandlerInterface;
use futuretek\openapi\Middleware\LoggerInterface;
use Psr\Http\Message\UploadedFileInterface;
use yii\web\Controller;
use yii\web\Response;

/**
 * Abstract base controller for OpenAPI-generated endpoints.
 *
 * Handles:
 * - Request body deserialization (JSON, multipart/form-data, x-www-form-urlencoded)
 * - File upload conversion to PSR-7 UploadedFileInterface
 * - Parameter injection into action methods (body + path/query/header/cookie)
 * - Response DTO serialization to JSON
 * - Authentication and authorization middleware
 * - Logging
 *
 * User controllers extend this class and implement the generated interface.
 */
abstract class AbstractApiController extends Controller
{
    /**
     * Override to disable CSRF for API controllers.
     */
    public $enableCsrfValidation = false;

    /**
     * Map of operationId => action metadata.
     * Generated by the code generator — override in generated abstract controller.
     *
     * Format:
     * ```
     * [
     *     'operationId' => [
     *         'bodyClass' => 'App\\Api\\Schemas\\CreatePetRequest',
     *         'bodyRequired' => true,
     *         'mediaType' => 'application/json',
     *         'security' => ['bearerAuth'],
     *         'params' => [
     *             ['name' => 'petId', 'in' => 'path', 'type' => 'string', 'required' => true],
     *         ],
     *     ],
     * ]
     * ```
     *
     * @var array<string, array>
     */
    protected array $operationMeta = [];

    /**
     * The controller/tag name for this controller.
     * Set by the generated abstract controller.
     */
    protected string $controllerTag = '';

    private AuthenticationInterface $authentication;
    private AuthorizationInterface $authorization;
    private LoggerInterface $logger;
    private FileHandlerInterface $fileHandler;

    public function init(): void
    {
        parent::init();

        $this->authentication ??= $this->createAuthentication();
        $this->authorization ??= $this->createAuthorization();
        $this->logger ??= $this->createLogger();
        $this->fileHandler ??= $this->createFileHandler();
    }

    /**
     * Override to provide custom authentication.
     */
    protected function createAuthentication(): AuthenticationInterface
    {
        return new DefaultAuthentication();
    }

    /**
     * Override to provide custom authorization.
     */
    protected function createAuthorization(): AuthorizationInterface
    {
        return new DefaultAuthorization();
    }

    /**
     * Override to provide custom logger.
     */
    protected function createLogger(): LoggerInterface
    {
        return new DefaultLogger();
    }

    /**
     * Override to provide custom file handler.
     */
    protected function createFileHandler(): FileHandlerInterface
    {
        return new DefaultFileHandler();
    }

    /**
     * Resolve the operationId from the action ID.
     */
    protected function resolveOperationId(string $actionId): ?string
    {
        // Action ID is like "create-pet", operation meta key is "createPet"
        // Generated meta uses operationId directly
        foreach ($this->operationMeta as $opId => $meta) {
            $expectedActionId = $this->operationIdToActionId($opId);
            if ($expectedActionId === $actionId) {
                return $opId;
            }
        }
        return null;
    }

    /**
     * Convert operationId (camelCase) to Yii2 action ID (kebab-case).
     */
    private function operationIdToActionId(string $operationId): string
    {
        return strtolower(preg_replace('/([a-z])([A-Z])/', '$1-$2', $operationId));
    }

    /**
     * @inheritDoc
     */
    public function beforeAction($action): bool
    {
        if (!parent::beforeAction($action)) {
            return false;
        }

        $operationId = $this->resolveOperationId($action->id);
        if ($operationId === null) {
            return true; // Not an API action, pass through
        }

        $meta = $this->operationMeta[$operationId] ?? null;
        if ($meta === null) {
            return true;
        }

        $this->logger->info("Request: {$this->controllerTag}/$operationId ({$action->id})", [
            'method' => \Yii::$app->request->getMethod(),
            'url' => $_SERVER['REQUEST_URI'] ?? '(unknown)',
            'contentType' => \Yii::$app->request->getContentType(),
        ]);

        // Authentication
        $security = $meta['security'] ?? [];
        if (!empty($security)) {
            try {
                $identity = $this->authentication->authenticate($operationId, $security);
                $this->logger->info("Authentication OK for $operationId", [
                    'security' => $security,
                    'identity' => $this->summarizeValue($identity),
                ]);
            } catch (\Throwable $e) {
                $this->logger->warning("Authentication FAILED for $operationId: {$e->getMessage()}", [
                    'security' => $security,
                ]);
                \Yii::$app->response->statusCode = 401;
                \Yii::$app->response->format = Response::FORMAT_JSON;
                \Yii::$app->response->data = ['error' => 'Unauthorized', 'message' => $e->getMessage()];
                return false;
            }

            // Authorization
            try {
                if (!$this->authorization->authorize($operationId, $identity, $this->controllerTag)) {
                    throw new \RuntimeException('Forbidden');
                }
                $this->logger->info("Authorization OK for $operationId", [
                    'controller' => $this->controllerTag,
                ]);
            } catch (\Throwable $e) {
                $this->logger->warning("Authorization FAILED for $operationId: {$e->getMessage()}", [
                    'controller' => $this->controllerTag,
                ]);
                \Yii::$app->response->statusCode = 403;
                \Yii::$app->response->format = Response::FORMAT_JSON;
                \Yii::$app->response->data = ['error' => 'Forbidden', 'message' => $e->getMessage()];
                return false;
            }
        } else {
            $this->logger->info("No security for $operationId — skipping auth");
        }

        return true;
    }

    /**
     * @inheritDoc
     *
     * Bind action parameters: body DTO + path/query/header/cookie params.
     */
    public function bindActionParams($action, $params): array
    {
        $operationId = $this->resolveOperationId($action->id);
        if ($operationId === null) {
            return parent::bindActionParams($action, $params);
        }

        $meta = $this->operationMeta[$operationId] ?? null;
        if ($meta === null) {
            return parent::bindActionParams($action, $params);
        }

        $request = \Yii::$app->request;
        $args = [];

        // Body parameter (always first if present)
        if (isset($meta['bodyClass'])) {
            $discriminator = $meta['discriminator'] ?? null;
            if (!empty($meta['bodyIsArray'])) {
                $body = $this->deserializeArrayBody($meta['bodyClass'], $meta['mediaType'] ?? 'application/json');
                $args[] = $body;
            } else {
                $body = $this->deserializeBody($meta['bodyClass'], $meta['mediaType'] ?? 'application/json', $discriminator);
                $args[] = $body;
            }
        } elseif (isset($meta['bodyType']) && !empty($meta['bodyIsArray'])) {
            $body = $this->deserializePrimitiveArrayBody($meta['bodyType'], $meta['mediaType'] ?? 'application/json');
            $args[] = $body;
        }

        // Remaining parameters: path, query, header, cookie
        $paramsMeta = $meta['params'] ?? [];
        $resolvedParams = [];
        foreach ($paramsMeta as $paramMeta) {
            $name = $paramMeta['name'];
            $in = $paramMeta['in'];
            $type = $paramMeta['type'] ?? 'string';
            $required = $paramMeta['required'] ?? false;
            $default = $paramMeta['default'] ?? null;
            $enumClass = $paramMeta['enumClass'] ?? null;

            $value = match ($in) {
                'path' => $params[$name] ?? null,
                'query' => $request->getQueryParam($name, $default),
                'header' => $request->getHeaders()->get($name, $default),
                'cookie' => $request->getCookies()->getValue($name, $default),
                default => $params[$name] ?? $default,
            };

            // Type cast
            $value = $this->castParameterValue($value, $type, $enumClass);

            $resolvedParams[$name] = $this->summarizeValue($value);
            $args[] = $value;
        }

        if (!empty($resolvedParams)) {
            $this->logger->info("Params for $operationId", $resolvedParams);
        }

        return $args;
    }

    /**
     * @inheritDoc
     *
     * Serialize response DTO to JSON automatically.
     */
    public function afterAction($action, $result): mixed
    {
        $operationId = $this->resolveOperationId($action->id);

        if ($operationId !== null && $result !== null && !($result instanceof Response)) {
            if ($result instanceof UploadedFileInterface) {
                // Binary file response — stream it as-is without JSON serialization.
                $response = \Yii::$app->response;
                $response->format = Response::FORMAT_RAW;
                $response->headers->set('Content-Type', $result->getClientMediaType() ?? 'application/octet-stream');
                if ($result->getClientFilename() !== null) {
                    $response->headers->set(
                        'Content-Disposition',
                        'attachment; filename="' . addslashes($result->getClientFilename()) . '"',
                    );
                }
                if ($result->getSize() !== null) {
                    $response->headers->set('Content-Length', (string) $result->getSize());
                }
                $response->content = $result->getStream()->getContents();
                $this->logger->info("Response: $operationId (binary file)", [
                    'status' => $response->statusCode,
                    'filename' => $result->getClientFilename(),
                    'size' => $result->getSize(),
                ]);

                return parent::afterAction($action, $response);
            }

            \Yii::$app->response->format = Response::FORMAT_JSON;
            $serialized = DataMapper::toArray($result);
            $this->logger->info("Response: $operationId", [
                'status' => \Yii::$app->response->statusCode,
                'data' => $this->summarizeData($serialized),
            ]);
            \Yii::$app->response->data = $serialized;
            $result = \Yii::$app->response;
        } elseif ($operationId !== null && $result === null) {
            $this->logger->info("Response: $operationId (void)", [
                'status' => \Yii::$app->response->statusCode,
            ]);
        }

        return parent::afterAction($action, $result);
    }

    /**
     * Deserialize request body into a typed DTO.
     *
     * @param class-string $dtoClass
     * @param array{propertyName: string, mapping: array<string, class-string>}|null $discriminator
     */
    private function deserializeBody(string $dtoClass, string $mediaType, ?array $discriminator = null): object
    {
        $request = \Yii::$app->request;

        $data = match (true) {
            str_contains($mediaType, 'json') => $this->parseJsonBody($request),
            str_contains($mediaType, 'multipart/form-data'),
            str_contains($mediaType, 'x-www-form-urlencoded') => $this->parseFormBody($request, $dtoClass),
            default => $this->parseJsonBody($request),
        };

        // Resolve concrete class via discriminator mapping
        if ($discriminator !== null) {
            $propName = $discriminator['propertyName'];
            $mapping = $discriminator['mapping'] ?? [];
            $discriminatorValue = $data[$propName] ?? null;

            if ($discriminatorValue !== null && isset($mapping[$discriminatorValue])) {
                $dtoClass = $mapping[$discriminatorValue];
                $this->logger->info("Discriminator resolved: $propName=$discriminatorValue → $dtoClass");
            } else {
                $this->logger->warning("Discriminator property '$propName' value '$discriminatorValue' not found in mapping, using default class $dtoClass");
            }
        }

        $this->logger->info("Body deserialized → $dtoClass", [
            'mediaType' => $mediaType,
            'data' => $this->summarizeData($data),
        ]);

        return DataMapper::toObject($data, $dtoClass);
    }

    /**
     * Parse JSON request body.
     */
    private function parseJsonBody(\yii\web\Request $request): array
    {
        $rawBody = $request->getRawBody();

        if ($rawBody === '' || $rawBody === false) {
            return [];
        }

        $data = json_decode($rawBody, true, 512, JSON_THROW_ON_ERROR);

        if (!is_array($data)) {
            throw new \RuntimeException('Invalid JSON body: expected object');
        }

        return $data;
    }

    /**
     * Parse form/multipart request body, including file uploads.
     *
     * @param class-string $dtoClass
     */
    private function parseFormBody(\yii\web\Request $request, string $dtoClass): array
    {
        $data = $request->getBodyParams();

        // Merge file uploads — detect file properties via reflection on the DTO class
        $refClass = new \ReflectionClass($dtoClass);
        foreach ($refClass->getProperties(\ReflectionProperty::IS_PUBLIC) as $property) {
            $type = $property->getType();
            $propName = $property->getName();

            if ($type instanceof \ReflectionNamedType && $type->getName() === UploadedFileInterface::class) {
                // Single file
                $file = \yii\web\UploadedFile::getInstanceByName($propName);
                if ($file !== null && $file->error !== UPLOAD_ERR_NO_FILE) {
                    $data[$propName] = $this->fileHandler->convertUploadedFile($file);
                    $this->logger->info("File upload: $propName", [
                        'name' => $file->name,
                        'type' => $file->type,
                        'size' => $file->size,
                    ]);
                }
            }

            // Array of files
            $arrayTypeAttrs = $property->getAttributes(\futuretek\datamapper\attributes\ArrayType::class);
            if (!empty($arrayTypeAttrs)) {
                $itemType = $arrayTypeAttrs[0]->newInstance()->of;
                if ($itemType === UploadedFileInterface::class) {
                    $files = \yii\web\UploadedFile::getInstancesByName($propName);
                    $validFiles = array_filter($files, fn($f) => $f->error !== UPLOAD_ERR_NO_FILE);
                    $data[$propName] = array_map(
                        fn($f) => $this->fileHandler->convertUploadedFile($f),
                        $validFiles,
                    );
                    $this->logger->info("File upload (array): $propName", [
                        'count' => count($validFiles),
                        'files' => array_map(fn($f) => [
                            'name' => $f->name,
                            'type' => $f->type,
                            'size' => $f->size,
                        ], $validFiles),
                    ]);
                }
            }
        }

        return $data;
    }

    /**
     * Cast a parameter value to the expected PHP type.
     */
    private function castParameterValue(mixed $value, string $type, ?string $enumClass): mixed
    {
        if ($value === null) {
            return null;
        }

        if ($enumClass !== null && enum_exists($enumClass)) {
            return $enumClass::tryFrom($value);
        }

        return match ($type) {
            'int' => (int)$value,
            'float' => (float)$value,
            'bool' => filter_var($value, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE) ?? (bool)$value,
            'string' => (string)$value,
            default => $value,
        };
    }

    /**
     * Deserialize a request body that is a JSON array of primitive values (e.g., int[], string[]).
     *
     * @param string $itemType The PHP scalar type of each item (int, float, string, bool, mixed)
     */
    private function deserializePrimitiveArrayBody(string $itemType, string $mediaType): array
    {
        $request = \Yii::$app->request;
        $rawBody = $request->getRawBody();

        if ($rawBody === '' || $rawBody === false) {
            $this->logger->info("Empty primitive array body ({$itemType}[])");
            return [];
        }

        $data = json_decode($rawBody, true, 512, JSON_THROW_ON_ERROR);

        if (!is_array($data) || (!empty($data) && !array_is_list($data))) {
            throw new \RuntimeException('Invalid JSON body: expected array');
        }

        $this->logger->info("Body deserialized → {$itemType}[]", [
            'mediaType' => $mediaType,
            'count' => count($data),
            'data' => $this->summarizeData($data),
        ]);

        return array_map(fn($item) => $this->castParameterValue($item, $itemType, null), $data);
    }

    /**
     * Deserialize a request body that is a JSON array of DTO objects.
     *
     * @param class-string $dtoClass The DTO class for each item
     */
    private function deserializeArrayBody(string $dtoClass, string $mediaType): array
    {
        $request = \Yii::$app->request;
        $rawBody = $request->getRawBody();

        if ($rawBody === '' || $rawBody === false) {
            $this->logger->info("Empty array body ({$dtoClass}[])");
            return [];
        }

        $data = json_decode($rawBody, true, 512, JSON_THROW_ON_ERROR);

        if (!is_array($data) || (!empty($data) && !array_is_list($data))) {
            throw new \RuntimeException('Invalid JSON body: expected array');
        }

        $this->logger->info("Body deserialized → {$dtoClass}[]", [
            'mediaType' => $mediaType,
            'count' => count($data),
        ]);

        return array_map(fn($item) => DataMapper::toObject($item, $dtoClass), $data);
    }

    /**
     * Summarize data for logging: truncate large arrays/strings, mask files.
     *
     * @return array|string|mixed
     */
    private function summarizeData(mixed $data, int $maxItems = 5, int $maxStringLength = 200): mixed
    {
        if (is_array($data)) {
            $isList = array_is_list($data);
            $count = count($data);

            if ($isList && $count > $maxItems) {
                $summarized = array_map(
                    fn($item) => $this->summarizeData($item, $maxItems, $maxStringLength),
                    array_slice($data, 0, $maxItems),
                );
                $summarized[] = "... +" . ($count - $maxItems) . " more items (total: $count)";
                return $summarized;
            }

            $result = [];
            foreach ($data as $key => $value) {
                $result[$key] = $this->summarizeData($value, $maxItems, $maxStringLength);
            }
            return $result;
        }

        if (is_string($data) && strlen($data) > $maxStringLength) {
            return substr($data, 0, $maxStringLength) . '... (' . strlen($data) . ' chars)';
        }

        if ($data instanceof UploadedFileInterface) {
            return '[File: ' . ($data->getClientFilename() ?? 'unknown') . ', ' . ($data->getSize() ?? '?') . ' bytes]';
        }

        return $data;
    }

    /**
     * Summarize a single value for logging (used for params and identity).
     */
    private function summarizeValue(mixed $value): mixed
    {
        if ($value === null) {
            return null;
        }

        if ($value instanceof UploadedFileInterface) {
            return '[File: ' . ($value->getClientFilename() ?? 'unknown') . ', ' . ($value->getSize() ?? '?') . ' bytes]';
        }

        if ($value instanceof \BackedEnum) {
            return $value->value;
        }

        if (is_object($value)) {
            // For identity objects and DTOs, convert to array summary
            if (method_exists($value, 'toArray')) {
                return $this->summarizeData($value->toArray());
            }
            return '[' . get_class($value) . ']';
        }

        if (is_array($value)) {
            return $this->summarizeData($value);
        }

        if (is_string($value) && strlen($value) > 200) {
            return substr($value, 0, 200) . '... (' . strlen($value) . ' chars)';
        }

        return $value;
    }
}
